// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEf2-Qggwv6G2_mpwZvyN_yH6RkSg6Oh0',
    appId: '1:377798620953:web:d7a05d19397348e3bc3788',
    messagingSenderId: '377798620953',
    projectId: 'safetynetapp-9b038',
    authDomain: 'safetynetapp-9b038.firebaseapp.com',
    storageBucket: 'safetynetapp-9b038.firebasestorage.app',
    measurementId: 'G-BB2HCF0V5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVTLavKpy2V2W2EOS8VNA8LwG0s_Yt78',
    appId: '1:377798620953:android:60c38fb77c2f2985bc3788',
    messagingSenderId: '377798620953',
    projectId: 'safetynetapp-9b038',
    storageBucket: 'safetynetapp-9b038.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyrHTvwaqCmwLzvww-F-IvljU_yisEUBM',
    appId: '1:377798620953:ios:8890ac53c3b1acd8bc3788',
    messagingSenderId: '377798620953',
    projectId: 'safetynetapp-9b038',
    storageBucket: 'safetynetapp-9b038.firebasestorage.app',
    iosBundleId: 'com.example.safetynetMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyrHTvwaqCmwLzvww-F-IvljU_yisEUBM',
    appId: '1:377798620953:ios:8890ac53c3b1acd8bc3788',
    messagingSenderId: '377798620953',
    projectId: 'safetynetapp-9b038',
    storageBucket: 'safetynetapp-9b038.firebasestorage.app',
    iosBundleId: 'com.example.safetynetMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEf2-Qggwv6G2_mpwZvyN_yH6RkSg6Oh0',
    appId: '1:377798620953:web:89b5fc8738b01ffdbc3788',
    messagingSenderId: '377798620953',
    projectId: 'safetynetapp-9b038',
    authDomain: 'safetynetapp-9b038.firebaseapp.com',
    storageBucket: 'safetynetapp-9b038.firebasestorage.app',
    measurementId: 'G-JDR3R0G6BF',
  );
}
